#!/bin/sh

# Run Maven tests
mvn clean test

# Check the result of the Maven test command
if [ $? -ne 0 ]; then
    echo "Maven tests failed. Commit aborted."
    exit 1
fi

# Run Checkstyle using Maven
#mvn clean checkstyle:check

# Check if Checkstyle found any violations
if [ $? -ne 0 ]; then
  mvn clean site
  echo "Checkstyle violations found. Fix them before committing."
  echo "Check the Checkstyle report in the 'target/site' directory."
  echo "Hendi Santika: $(date)"
  exit 1
fi
